module.exports = {
  project1: {
    name: 'AngularJS Sort Function',
    image: 'Angular-Sort.jpg',
    desc: 'Most of my time spent at my internship at Devetry involved working with the AngularJS framework. I loved working with this javaScript framework and hope to get chances to work with this in the future! One of my primary tasks while working here was to develop a custom sort on a few of the tables on a project with an enormous codebase. This was interesting as I have not worked with a codebase so large before. After looking up a few things and going through a tutorial or two, I felt comfortable tackling this challenge. My first attempt looked promising as I used a function called by the ng-click directive to allow clicking on the table header title of each column to sort the column by ascending or descending order. The only issue was that there was nothing showing that this functionality was available at first glance without knowing the functionality was there. My solution to this was returning the arrow-down class on the else statement instead of a blank string! This solution shows the sort arrow next to the header title at all times, which shows the user that this sort capability is available just by looking at the table. This functionality pairs perfectly with the filter functionality described in the next project on my portfolio. To see a working demo and corresponding code for this project please see the JSFiddle below.',
    havLink: true,
    link: 'http://jsfiddle.net/Zucktime12/yo32tdm4/2/embedded/result',
    tag: "AngularJS",
  },
  project2: {
    name: 'AngularJS Filter on a table',
    image: 'Angular-Filter.jpg',
    desc: 'Another one of my primary tasks while working here was to develop a filter on a table which allows the user to search by any of the columns. The greatest challenge to creating this was trying to get the filter to actually filter by each corresponding column as this was my first experience with AngularJS. Also, a difficult function to figure out was being able to filter multiple columns at the same time. Originally I had written a complex function that worked, but there was a much simpler way to get AngularJS to do exactly what I wanted to do. This functionality pairs perfectly with the sort function described in my first portfolio item allowing the use of a table with both filter and sort capabilities! This was truly a great learning experience and amazing introduction to a language I fell in love with. Please see JSFiddle below for the demo and corresponding code.',
    havLink: true,
    link: 'http://jsfiddle.net/Zucktime12/bzqa32s8/result',
    tag: "AngularJS",
  },
  project3: {
    name: 'Photo Gallery Search',
    image: 'responsive-photo-gallery.jpg',
    desc: 'This project was one of my favorite in learning JavaScript and jQuery. It also allowed me to reinforce some of my html and css skills. I started the project by building out the gallery using HTML and CSS to follow the design of the mockup provided to me. My next step was to find a plugin for a lightbox feature. I researched and found the plugin Magnific Popup, which I loved! I was able to implement this into my project fairly easily and formatted the lightbox to look identical to the mockup with the caption centered below the image. The most daunting part of this project was creating the search box that allows the user to search images by the caption and only show results matching what is input into the search box. After many failed plugin attempts I decided to research how I could code this my self with JavaScript. I researched and found what I needed to make this work with some simple JavaScript and jQuery. I had to target my searchbox with an ID and make a function that ran on each keyup so that the searchbox would search in live time. The function logged the value of the user input and converted each value to lowercase so there would be no discrepancy regardless of the user typing in upper or lowercase. The function then would hide or show images in the gallery based on if the input from the user matched anything in the caption text. See the JSfiddle below for the demo.',
    havLink: true,
    link: 'http://jsfiddle.net/Zucktime12/a4mfdw4m/embedded/result',
    tag: "HTML, CSS",
  },
  project4: {
    name: 'Javascript Drawing Application',
    image: 'drawing-add.jpg',
    desc: 'This project was one of the coolest ones I created. This demo was taught to me from one of my courses. This simple drawing application allows the user to either choose from the preset color pallet or create their own color to add to the pallet to draw with. The html template was provided to me with none of the JavaScript or jQuery functionality working. The first major problem was to figure out how to get the new color button to work and toggle the screen that accessed the sliders used for color creation! I did this by setting each of the sliders to have a range from 0 to 255 to include the entire color spectrum. Once this is selected by the user the colors are logged into an RGB element to produce a color. This color is previewed to the left of the sliders so the user can see what they are adding to the pallet. The next part of the project invloced appending the new color to the pallet when the user clicks the "Add Color" button. At this point, I was learning a lot about the .append and .click commands in order to make the new color active as the user clicked the "Add Color" button. The final part of the project was getting the user to be able to physically draw on the canvas with the colors they selected. This process familiarized me with the .mouseDown, .mousemove, and .mouseup events to get the application to correctly draw only when the user has the mouse clicked down and moves to any point on the canvas. See the JSfiddle below for a demo of this project.',
    havLink: true,
    link: 'http://jsfiddle.net/Zucktime12/t9wwnqfj/embedded/result',
    tag: "JavaScript",
  },
  project5: {
    name: 'Media Query Project',
    image: 'mq-desk-main.jpg',
    desc: 'This responsive layout project was really interesting. This put to the test my knowledge of media queries to implement 3 different portfolio designs at the mobile, tablet, and desktop views. I began this project by establishing the HTML and CSS for the mobile mockup. After getting all of the functionality of the portfolio at the mobile level, I created a media query for the tablet view which changed the navigation, header, and portfolio gallery. In the mobile view everything was stacked on top of eachother so everything could easily be viewed by the user scrolling down. The first step was to set the max width of the container to the tablet view (768px). I set the display of the navigation to inline block so each navigation option was displayed next to eachother under my name. Then to address the portfolio gallery design I set the font size of the list items to 0. Then I set the display of the list items to inline block with a width of 50% to make sure they would only display 2 images per row. I reset the font size to initial and the result turned out great! For the desktop display I made another change to the navigation by floating it to the right so it no longer appeared under my name. I had a very similar approach to the portfolio gallery as they wanted 3 images per row in the desktop view. To make this work I simply set the new width of the list items to 33.3333% to make them display 3 images across. To see a working demo of this please click the "Edit in JSFiddle" in the top right of the JSFiddle below.',
    havLink: true,
    link: 'http://jsfiddle.net/Zucktime12/dcsfuu08/embedded/result',
    tag: "HTML, CSS",
  },
  project6: {
    name: 'Javascript Quiz',
    image: 'javascript-quiz.jpg',
    desc: 'This project is a JavaScript quiz that will ask the user 3 questions that started in an array. After the user submits their answer to the 3 questions. The JavaScript program will tell the user how many questions they got right. The program will also tell the user which questions they answered correct and incorrect. This project was a great for practicing JavaScript. I utilized and gained better knowledge of the .push and return commands as well as logging items to an array, which became very useful in other projects, such as my Photo Gallery Search box. This project also allowed me to practice loops, which were difficult to grasp, but practicing on projects like this help better understand them. Please see the demo below on JSFiddle.',
    havLink: true,
    link: 'http://jsfiddle.net/Zucktime12/664f4xbx/embedded/result',
    tag: "JavaScript",
  },
  project7: {
    name: 'Registration Form Styles',
    image: 'registration1.jpg',
    desc: 'This was my first project creating an online registration form. First, I used HTML and CSS to build out the form to match the mockup. I used differnt input types like text, email, checkboxes, and radio buttons. Also, one of the sections utilized a select box used to choose from a list of states as well as a textarea element to allow users to input comments at the bottom. One of the biggest challenges during this project was getting the labels that describe each input field to display on the left of the input field instead of over them. To fix this, I wrapped each pair of labels and inputs into a div element with the class "block". After that, I was able to display them inline block. The final part was to set each elements width so the content would display identical to the mockup! Please see the demo below on JSFiddle.',
    havLink: true,
    link: 'http://jsfiddle.net/Zucktime12/vr1L1gdo/embedded/result',
    tag: "HTML, CSS",
  },
  project8: {
    name: 'End to End Testing',
    image: 'E2E-tests-1.png',
    desc: 'During my internship with Devetry, one of the most important things I worked on was End to End testing using protractor. This was a difficult task at first as this was my first experience with such a large codebase as well as my first experience with Protractor. Practicing writing end to end tests for the application signifincantly improved my understanding of the AngularJS framework as well as provding me a good base knowledge of End to End testing in general. Over the course of a few weeks I was writing my own tests for new pieces of the application being developed. Please see the above code snippets for some of my examples of End to End tests I wrote during my time at Devetry.',
    havLink: false,
    link: '',
    tag: "AngularJS, Protractor",
  },
  project9: {
    name: 'Responisve Pet Photography Site',
    image: 'PetPhotographySite.png',
    desc: 'This was a very exciting project as I wanted to create an actual product from scratch! My girlfriend and I had always talked about doing pet photography on the side so why not build an entire site for this business model. I found a design I liked on pintrest and chose to mimic this using HTML, CSS, as well as JavaScript. This was a very fun project to build and I feel I did an excellent job creating multiple breakpoints and starting my design from Mobile up. I was able to build this responsive website from start to finish in just one day! I chose to use flexbox options for spacing as they are very responsive and easy to manage the space how I see fit best! I really enjoy using the flexbox as it is what I have found to be the fastest method for moving objects inline with eachother. This also eliminates certain instances where floats can get messy. I feel this site looks great and has great potential to be a driver for business for a Pet Photography business. Please click the button below to see the site!',
    havLink: true,
    link: 'http://brandonzucker.com/PetPhotography/index.html',
    tag: "HTML, CSS, JavaScript",
  },
  project10: {
    name: 'Stained Glass WooCommerce Site (Wordpress)',
    image: 'bethanieglass.png',
    desc: 'This site was very fun to build as it was my first true custom Wordpress project. This is a responsive Wordpress site utilizing the WooCommerce plugin. The site is for a stained glass company. Some of the challenges of this project were figuring out the wordpress custom themes and how to properly use Php for wordpress to bring in different pieces of content such as the header and footer on each page as well as the nav menu. Creating this project helped me immensly in learning the ins and outs of wordpress as well as how to construct a custom theme, which is very important.',
    havLink: true,
    link: 'http://brandonzucker.com/bethanie',
    tag: "Wordpress, WooCommerce",
  },
  project11: {
    name: 'HTML5 Canvas',
    image: 'Canvas-DrawingApp-VanillaJS.png',
    desc: 'This project is slightly different from the previous drawing application I created. In this project I used a flag to make it so the user would only draw on the canvas when the mousdown event is triggered. The variable isDrawing is initially set to false and this is switched to true when the user fires the mousedown event. Once the mouseup event is fired by the user the drawing will stop. In order to be able to draw on the canvas we used the offsetX and offsetY properties to tell the program to only draw where the mouse is clicked down. I achieved this by initially starting the offsetX and offsetY values to 0 but updating the values to where the mouse location is once the user clicks down or fires the mousedown event. Unlike my other drawing application the user is unable to choose a color in this project. Instead by using the hsl property, the color constantly changes based on this hsl value as the user draws. This was a really cool feature to learn and the colors will continue to cycle as long as the user continues to draw. Another new feature I learned was making the line width increase or decrease as the user draws on the canvas. For this we set the linewidth of the to a certain length and increased or decreased the value as the user moves the mouse to draw. I implemented a function to switch directions once the width reached a certain value so once you reach the min or max value it will begin to increase or decrease the opposite direction creating a really cool drawing effect as seen in the screenshot. I have created a JSfiddle for this application so try it out yourself by clicking the link below and simply begin drawing!',
    havLink: true,
    link: 'http://jsfiddle.net/Zucktime12/htbb17gw/embedded/result/',
    tag: "JavaScript",
  },
  project12: {
    name: 'Checkbox Select by holding Shift',
    image: 'hold-shift-to-check-multiple-inputs.png',
    desc: 'I enjoyed this project because it made me think about how to solve something a lot of people use for things such as Email. This is an important feature that took some thinking to figure out. The main issue with this is figuring out how to get all the boxes inbetween the two boxes you select to be checked. In order to achieve this we first had to loop through all of the possible boxes and then identify the two selected by the user with an if statement. We then have a flag variable which is initially set to false but inside the if statement set it to !variable or opposite of the variable. So another if statement saying if the inBetween variable is set to true check the boxes inbetween the users selections. We use the !variable to make sure this will work from top to bottom or vice versa. While this was not a lot of code actually written for this project, it did require some thought as to how to accomplish the feat of the project. Please see a demo at the link below.',
    havLink: true,
    link: 'http://jsfiddle.net/Zucktime12/ceb6yw4y/embedded/result/',
    tag: "JavaScript",
  },
  project13: {
    name: 'Custom Video Player',
    image: 'custom-video-player-vanillaJS.png',
    desc: 'This project was fun as I do not spend much time working with video players or creating custom controls for them. This project really helped me understand how to organize my javascript code. I broke it down into getting the elements, building out functions, and hooking up the event listeners. This project was great practice for editing video elements and creating a custom player with custom controls. ',
    havLink: true,
    link: '',
    tag: "JavaScript",
  },
  project14: {
    name: 'KidderPlus.com',
    image: 'KidderPlus.png',
    desc: "Most of the clients I worked for at New Media One were real estate clients located around Boulder, CO. This site was fun to work on because it allowed me to learn more about the ins and outs of Wordpress. Prior to this gig I had only done a couple Wordpress sites with custom themes. Though not all of these projects were custom themes I still had to learn to navigate Wordpress as well as the SFTP it was hosted on (I eventually convinced them to move to git). This was by far my largest struggle to begin with. It was not necessarily the work that was hard, rather finding where to perform the styling, Javascript and HTML. This was not a custom theme but I did create some custom functionalities on the site. I was responsible for majority of the styling on this site, specifically the agents cover photo on the home page. The first time I did this it was requested that each agent has a photo with a border. Then there was a great background photo of Boulder, CO. Over the photo was a light blue overlay.  This was later asked to be changed to a group photo where you should be able to hover over each agent to reveal their name and when clicked would route the user to the real estate agent's about me page. This was a great learning experience as I found a perfect plugin to implement this feature. The hardest part of this task was finding the spot to initiate the hover which showed the agent name. The plugin simply asked for the coordinates on the page that corresponded with the agents face. Then you would type the name you want to appear and select the styling of the hover state which I matched to their sites primary color. I found these positions by logging the click of my mouse to the console to get the x and y coordinates of each agent. As you can see the feature works great and links to each agent properly.",
    havLink: true,
    link: 'Kidderplus.com',
    tag: "Wordpress",
  },
  project15: {
    name: 'JenRealty.com',
    image: 'Jen-Realty.png',
    desc: 'JenRealty was another Boulder, CO real estate client we made a site for. I was also responsible for a good amount of the styling on this site. This site primarily got me a lot of good experinece with wordpress and doing more custom CSS.',
    havLink: true,
    link: 'jenrealty.com',
    tag: "Wordpress",
  },
  project16: {
    name: 'The Mason',
    image: 'The-Mason.png',
    desc: 'The Mason was one of my first and favorite projects to work on at Outspoke. They are a high end apartment complex in St. Petersburg, FL. We host most of the sites we build on Flywheel which was a service I had to learn. This specific project I was in charge of building out pages and the site according to a composition in the program Sketch App. This program is great for the designer to hand off to the developer in order to copy the design. <br> Wordpress and CSS were my biggest skills learned and practiced on this project. This was my first taste of the Salient theme, which is the most common theme we use to build sites for clients. Aside from learning the different common layouts for pages, I learned a ton about Salient settings and how they can make a site build significantly smoother. I did build a custom navigation with CSS and Jquery which is the part of the site I was most proud of. This was a great start to improving my wordpress knowledge and I truly felt like my development skills improved after working on this project.',
    havLink: true,
    link: 'themasonstpete.com',
    tag: "Wordpress",
  },
  project17: {
    name: 'Westminster Manor',
    image: 'WestminsterManor.png',
    desc: 'Westminster Manor was another Salient theme build we created at Outspoke. I wound up touching this project after it was mostly built out. I took a development list created by our client and touched up a lot of the site. This was mostly CSS as spacing, fonts and some key functionalities were not working properly. This was a great learning experience for me as this was the first project I was really taking the reigns on. I was in constant contact with the client and took client calls whenever they had additional edits or saw other issues that needed to be addressed. The most interesting thing I did on this site was work with a plugin called Image Map Pro. Since this was an apartment complex this feature was used to show the availability of the units in the 2 buildings that make up Westminster Manor. This plugin is awesome and allows you to take a picture (in this case a blueprint of the buildings and units) and select each point for the highlighted hover state. This hoverstate had an overlay which would tell the user if a unit was available or unavailable. You could also click into the unit to bring up a modal that had specific details and layout pictures of the selected unit. <br> The initial build before I touched the site was setup using the incorrect building blueprints, so when I was given the updated blueprints I had to go through and reselect all of the points for the hover state which took a little bit of time to figure out the correct way of doing this. I was able to reference the first set of blueprints to figure out how to correctly mark up the updated set. After this I was tasked with creating content blocks to open as modals when a certain section was clicked by the user. This was achieved by creating each content block which had an associcated shortcode with each. There was a section of each piece in the Image Map Pro plugin for each building where I could input each shortcode into the area clicked so the plugin knew which modal to open for each unit. The only other item for this site was scaling down everything, including this image map pro section for mobile responsiveness.',
    havLink: true,
    link: 'westminstermanortampa.com',
    tag: "Wordpress/Plugins",
  },
  project18: {
    name: 'Duncan McClellan Gallery Glass and Duncan McClellan Gallery School Project',
    image: 'dmglass.png',
    desc: 'Duncan McClellan Gallery is an Outspoke client I worked with on monthly support for two sites we had already built for them. This is a really cool client who features over 90 glass blowing artists. The school project was created to give disadvantage youth a chance to learn about glass blowing as well as provide mentors to them. A lot of what I did for this client would be small changes to their site such as adding a new artist to their list. Other small edits included fixing styling on a new section that the client created. I basically was in constant contact with the client and would handle edits on support tickets as they would come through. Even though these were small edits normally, it assisted me a lot in learning how to navigate Wordpress as a whole and get a little quicker at small HTML and CSS edits.',
    havLink: true,
    link: 'dmglass.com',
    tag: "Wordpress/Plugins",
  },
  project19: {
    name: 'Car Candy',
    image: 'CarCandy.png',
    desc: 'This project was unique in that it was redesigned a few times in order to please the client. I was the primary developer on this site. I helped build out the majority of the pages as well as handled almost all of the styling across the site. I am very happy with how this site came along. Though this is not a live site currently, it should go live sometime in August. This site allowed me to get a better grasp on WooCommerce as well as the settings that go along with the WooCommerce plugin. One of the biggest things I learned from this project was how to get products into different categories and have them filter. Some of this was achieved through WooCommerce settings and the styling was addressed with CSS. I also learned how to correctly style the Cart and Checkout pages. One of the coolest features on this site used a feature called image with hot spots. Basically this would take an image (we used a high end car with the company logo on it) and created different spots on the car that the user can click to find out different information about the products the company sells. I also linked all of these titles so when the user clicks one, it will bring them to the respective products in the WooCommerce Shop.',
    havLink: false,
    link: '',
    tag: "Wordpress/Plugins",
  },
  project20: {
    name: 'Osteria',
    image: 'Osteria.png',
    desc: 'Osteria was a fun project that allowed me to learn a few more important things about Wordpress. Another big client request was to make the site animations look like another sites animations where the pictures will fade in as the user scrolls down the page. The site they referenced also had some animation delays to give a really cool effect where the images would pop in at different times. I achieved this by setting the animation in the visual composer but there were no settings to delay the animation. My solution to this was to add a custom CSS class to each image and then set a delay on this class. I created a few unique classes to set the images on different delays which created a really cool effect and was exactly what the client wanted. I also learned a new CSS property that allowed an image to be spliced and repeated around a border. This option fixed my first attempt at solving this as I tried setting the image as a background image, but this did not allow the ability to keep this responsive on the page. This also caused the background image to be cut off when the screen was scaled down as well and was just not a great option for what was needed. <br> The properties used in the best solution were border-image-source, border-image-slice, and border-image-repeat. The source provided the circle pattern used around some of the content blocks, while the border-image-slice property cut the pattern down to one of its cirlces. The border-image-repeat was set to round which allows the pattern we previously sliced to be tiled around the specified element. The property then tiles this pattern around the element and if it cannot be completed with a whole number of tiles, the tile is then scaled down to fit the border. The final part to this solution was adding the border to the inside of the pattern we just repeated. Initially when I set the border it moved to the outside of the circles and the client specifically asked the border to be on the inside of the repeated circle pattern. The solution to this was setting the border offset to bring the border inside the repeated pattern. This turned out amazing and the client was so happy with the result, which was so great to hear as a developer. ',
    havLink: false,
    link: '',
    tag: "Wordpress",
  },
  project21: {
    name: 'Northern Ice',
    image: 'northernice.png',
    desc: 'This site was interesting in that I was only asked to do some CSS edits on the Checkout totals. My primary task was to set up WooCommerce shipping options with FedEx. This was difficult because I have not had any prior experience with WooCommerce or configuring any of the options. In order to find out how to properly configure the WooCommerce settings as well as set up a coupon code the client I went through a lot of the WooCommerce documentation. Going through documentation and being able to implement specifically what you are looking for is a very important skill to have as a developer. I was able to successfully implement everything the client wanted and test to make sure everything was working before handing the project back off to the client.',
    havLink: true,
    link: 'northernice.life',
    tag: "Wordpress/Plugins",
  },
  // project22: {
  //   name: '',
  //   image: '',
  //   desc: '',
  //   havLink: true,
  //   link: 'northernice.life',
  //   tag: "Wordpress/Plugins",
  // },
};
